### ISSUE TITLE
machine :converge_only ignores chef_server param when run via chef-zero

### ISSUE THREAD

**Issue by hh** [chef-boneyard/chef-provisioning#448]
:converge_only results in a local_url of chefzero://localhost:8889 even though I have a with_chef_server block.

This does not happen with action `:setup`

I'm not sure if this is windows specific. I haven't tested linux yet.

``` ruby
require 'chef/provisioning/aws_driver'
with_chef_server "https://api.chef.io/organizations/#{ENV['CHEF_ORG']}",
                 :client_name => Chef::Config[:node_name],
                 :signing_key_filename => Chef::Config[:client_key]
machine "windows_node" do
  action :converge_only
end
```

```
$ chef-client -z converge_only_please.rb 
Starting Chef Client, version 12.4.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
Converging 1 resources
Recipe: @recipe_files::/home/hh/provisioning/converg_only_please.rb
  * machine[windows_node] action converge_only
[101, 110] in /home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provisioning/transport/winrm.rb
   101:       end
   102: 
   103:       def make_url_available_to_remote(local_url)
   104:         uri = URI(local_url)
   105:         byebug
=> 106:         host = Socket.getaddrinfo(uri.host, uri.scheme, nil, :STREAM)[0][3]
   107:         if host == '127.0.0.1' || host == '::1'
   108:           raise 'Unable to converge locally via winrm. Local converge is currently only supported with SSH. You may only converge with winrm against a chef-server.'
   109:         end
   110:         local_url
(byebug) local_url
chefzero://localhost:8889
(byebug) Socket.getaddrinfo(uri.host, uri.scheme, nil, :STREAM)[0][3]
*** SocketError Exception: getaddrinfo: Servname not supported for ai_socktype


(byebug) [2015-09-19T06:29:24-04:00] FATAL: SIGINT received, stopping
[2015-09-19T06:29:24-04:00] FATAL: SIGINT received, stopping


    ================================================================================
    Error executing action `converge_only` on resource 'machine[windows_node]'
    ================================================================================

    SystemExit
    ----------
    exit

    Resource Declaration:
    ---------------------
    # In /home/hh/stratalux/lifelock/misc/provisioning/from_image.rb

     43: machine "#{machine_name}" do
     44:   action :converge_only
     45: end

    Compiled Resource:
    ------------------
    # Declared in /home/hh/stratalux/lifelock/misc/provisioning/from_image.rb:43:in `from_file'

    machine("windows_node") do
      action [:converge_only]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"https://api.chef.io/organizations/my_customer", :options=>{:client_name=>"hippiehacker", :signing_key_filename=>"/home/hh/provisioning/.chef/hippiehacker.pem", :api_version=>"0"}}
      driver "aws::us-west-2"
      machine_options {:bootstrap_options=>{:instance_type=>"c3.2xlarge", :subnet_id=>"windows_subnet", :security_group_ids=>["windows_security_group"]}, :aws_tags=>{:created_by=>"chris", :please_destroy=>"true"}, :image_id=>"ami-d00dd00d"}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/home/hh/provisioning/converge_only.rb"
      run_list_modifiers [....]
    end

Running handlers:
[2015-09-19T06:29:24-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-09-19T06:29:24-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 75.492446348 seconds
[2015-09-19T06:29:25-04:00] FATAL: Stacktrace dumped to /home/hh/provisioning/.chef/local-mode-cache/cache/chef-stacktrace.out
[2015-09-19T06:29:25-04:00] ERROR: machine[windows_node] (@recipe_files::/home/hh/provisioning/converge_only_please.rb line 43) had an error: SystemExit: exit
```

```
Generated at 2015-09-19 06:29:25 -0400
SystemExit: machine[windows_node] (@recipe_files::/home/hh/provisioning/converge_only_please.rb line 43) had an error: SystemExit: exit
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:404:in `exit'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:404:in `fatal!'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:65:in `block in setup_signal_handlers'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interfaces/local_interface.rb:21:in `call'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interfaces/local_interface.rb:21:in `readline'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interfaces/local_interface.rb:21:in `readline'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interface.rb:68:in `prepare_input'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interface.rb:52:in `read_input'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/interface.rb:35:in `read_command'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/processors/command_processor.rb:139:in `repl'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/processors/command_processor.rb:95:in `process_commands'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/processors/command_processor.rb:75:in `at_line'
/home/hh/.rvm/gems/ruby-2.2.0/gems/byebug-6.0.2/lib/byebug/context.rb:109:in `at_line'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provisioning/transport/winrm.rb:106:in `make_url_available_to_remote'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provisioning/machine/basic_machine.rb:75:in `make_url_available_to_remote'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb:43:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provisioning/convergence_strategy/install_msi.rb:53:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provisioning/machine/basic_machine.rb:21:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-provisioning-1.4.0/lib/chef/provider/machine.rb:82:in `block in <class:Machine>'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:46:in `block in action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/provider.rb:140:in `run_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource.rb:584:in `run_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:49:in `run_action'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `each'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block in converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/runner.rb:80:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:654:in `block in converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `catch'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `converge'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:688:in `converge_and_save'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/client.rb:269:in `run'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:224:in `block in run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:212:in `run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `loop'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application/client.rb:382:in `run_application'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/lib/chef/application.rb:60:in `run'
/home/hh/.rvm/gems/ruby-2.2.0/gems/chef-12.4.1/bin/chef-client:26:in `<top (required)>'
/home/hh/.rvm/gems/ruby-2.2.0/bin/chef-client:23:in `load'
/home/hh/.rvm/gems/ruby-2.2.0/bin/chef-client:23:in `<main>'
```

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
