### ISSUE TITLE
winrm-elevated is a dependency of Chef Provisioning

### ISSUE THREAD

**Issue by monkey1016** [chef-boneyard/chef-provisioning#566]
Hi,
I think `winrm-elevated` should be added as a dependency to the Chef Provisioning gemspec.

When trying to run chef-provisioning, I get this stack trace if `winrm-elevated` isn't part of my Gemfile:
```
>>>> Caused by LoadError: cannot load such file -- winrm-elevated
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/transport/winrm.rb:4:in `require'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/transport/winrm.rb:4:in `<top (required)>'
```

Here's the whole stack trace if you need it.
```
Generated at 2017-02-23 15:15:18 -0500
LoadError: machine_batch[platform cluster create] (@recipe_files::C:/ncrdev/source/git/chef-provisioning-nep/chef-provisioning/vcair/vcair_nep_provisioning/recipes/deca_provisioning_create.rb line 43) had an error: LoadError: cannot load such file -- winrm-elevated
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/transport/winrm.rb:4:in `require'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/transport/winrm.rb:4:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/fog_driver/driver.rb:13:in `require'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/fog_driver/driver.rb:13:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/driver_init/fog.rb:1:in `require'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/driver_init/fog.rb:1:in `<top (required)>'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:56:in `require'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:56:in `rescue in rescue in driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:50:in `rescue in driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:47:in `driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:138:in `block in by_new_driver'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:136:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:136:in `by_new_driver'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:28:in `block in <class:MachineBatch>'
(eval):2:in `block in action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:102:in `with_ready_machines'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:51:in `block in <class:MachineBatch>'
(eval):2:in `block in action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bin/chef-client:22:in `load'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bin/chef-client:22:in `<main>'

>>>> Caused by LoadError: cannot load such file -- chef_metal/driver_init/fog
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:51:in `require'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:51:in `rescue in driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:47:in `driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:138:in `block in by_new_driver'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:136:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:136:in `by_new_driver'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:28:in `block in <class:MachineBatch>'
(eval):2:in `block in action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:102:in `with_ready_machines'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:51:in `block in <class:MachineBatch>'
(eval):2:in `block in action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bin/chef-client:22:in `load'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bin/chef-client:22:in `<main>'

>>>> Caused by LoadError: cannot load such file -- winrm-elevated
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/transport/winrm.rb:4:in `require'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/transport/winrm.rb:4:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/fog_driver/driver.rb:13:in `require'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/fog_driver/driver.rb:13:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/driver_init/fog.rb:1:in `require'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bundler/gems/chef-provisioning-fog-b0f322c8d74e/lib/chef/provisioning/driver_init/fog.rb:1:in `<top (required)>'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:48:in `require'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning.rb:48:in `driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:138:in `block in by_new_driver'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:136:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:136:in `by_new_driver'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:28:in `block in <class:MachineBatch>'
(eval):2:in `block in action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:102:in `with_ready_machines'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-2.1.1/lib/chef/provider/machine_batch.rb:51:in `block in <class:MachineBatch>'
(eval):2:in `block in action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bin/chef-client:22:in `load'
C:/Users/kj185064/AppData/Local/chefdk/gem/ruby/2.3.0/bin/chef-client:22:in `<main>'
```

**Comment by bradwilliamson** [comment]
I am also getting this error with ChefDK 1.2.22. I was about to submit the issue as well.  The issue was not there on 1.1.16. I was using the chef-provisioning-vsphere driver which failed.

**Comment by rjaros87** [comment]
:+1:

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
